import { SvgParams, DEFAULTS } from './types';

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function sanitizeColor(color: string, fallback: string): string {
  const sanitized = color.replace(/[^0-9A-Fa-f]/g, '');
  if (![3, 4, 6, 8].includes(sanitized.length)) {
    return fallback;
  }
  return '#' + sanitized;
}

function sanitizeFont(font: string): string {
  return font.replace(/[^0-9A-Za-z\- ]/g, '');
}

export function generateSvg(params: SvgParams): string {
  const separator = params.separator ?? DEFAULTS.separator;
  const random = params.random ?? DEFAULTS.random;
  
  // Process lines
  let lines: string[];
  if (Array.isArray(params.lines)) {
    lines = params.lines;
  } else {
    lines = params.lines.split(separator).filter(l => l.length > 0);
  }
  
  if (random) {
    lines = lines.sort(() => Math.random() - 0.5);
  }
  lines = lines.map(escapeHtml);

  const font = sanitizeFont(params.font ?? DEFAULTS.font);
  const weight = params.weight ?? DEFAULTS.weight;
  const color = sanitizeColor(params.color ?? DEFAULTS.color, DEFAULTS.color);
  const background = sanitizeColor(params.background ?? DEFAULTS.background, DEFAULTS.background);
  const size = params.size ?? DEFAULTS.size;
  const center = params.center ?? DEFAULTS.center;
  const vCenter = params.vCenter ?? DEFAULTS.vCenter;
  const width = params.width ?? DEFAULTS.width;
  const height = params.height ?? DEFAULTS.height;
  const multiline = params.multiline ?? DEFAULTS.multiline;
  const duration = params.duration ?? DEFAULTS.duration;
  const pause = params.pause ?? DEFAULTS.pause;
  const repeat = params.repeat ?? DEFAULTS.repeat;
  const letterSpacing = params.letterSpacing ?? DEFAULTS.letterSpacing;

  const lastLineIndex = lines.length - 1;
  let pathsAndText = '';

  for (let i = 0; i <= lastLineIndex; i++) {
    let animateElement: string;
    
    if (!multiline) {
      // Single line mode
      let begin = `d${i - 1}.end`;
      if (i === 0) {
        begin = repeat ? `0s;d${lastLineIndex}.end` : '0s';
      }
      const freeze = !repeat && i === lastLineIndex;
      const yOffset = height / 2;
      const emptyLine = `m0,${yOffset} h0`;
      const fullLine = `m0,${yOffset} h${width}`;
      const values = [emptyLine, fullLine, fullLine, freeze ? fullLine : emptyLine];
      const keyTimes = [
        '0',
        String((0.8 * duration) / (duration + pause)),
        String((0.8 * duration + pause) / (duration + pause)),
        '1',
      ];
      
      animateElement = `<animate id='d${i}' attributeName='d' begin='${begin}'
        dur='${duration + pause}ms' fill='${freeze ? 'freeze' : 'remove'}'
        values='${values.join(' ; ')}' keyTimes='${keyTimes.join(';')}' />`;
    } else {
      // Multiline mode
      const nextIndex = i + 1;
      const lineHeight = size + 5;
      const lineDuration = (duration + pause) * nextIndex;
      const yOffset = nextIndex * lineHeight;
      const emptyLine = `m0,${yOffset} h0`;
      const fullLine = `m0,${yOffset} h${width}`;
      const values = [emptyLine, emptyLine, fullLine, fullLine];
      const keyTimes = ['0', String(i / nextIndex), String(i / nextIndex + duration / lineDuration), '1'];
      
      animateElement = `<animate id='d${i}' attributeName='d' begin='0s${repeat ? `;d${lastLineIndex}.end` : ''}'
        dur='${lineDuration}ms' fill="freeze"
        values='${values.join(' ; ')}' keyTimes='${keyTimes.join(';')}' />`;
    }

    pathsAndText += `
    <path id='path${i}'>
      ${animateElement}
    </path>
    <text font-family='"${font}", monospace' fill='${color}' font-size='${size}'
      dominant-baseline='${vCenter ? 'middle' : 'auto'}'
      x='${center ? '50%' : '0%'}' text-anchor='${center ? 'middle' : 'start'}'
      letter-spacing='${letterSpacing}'>
      <textPath xlink:href='#path${i}'>
        ${lines[i]}
      </textPath>
    </text>`;
  }

  return `<!-- Generated by typing-svg-action -->
<svg xmlns='http://www.w3.org/2000/svg'
    xmlns:xlink='http://www.w3.org/1999/xlink'
    viewBox='0 0 ${width} ${height}'
    style='background-color: ${background};'
    width='${width}px' height='${height}px'>
${pathsAndText}
</svg>`;
}
